### ISSUE TITLE
[FEATURE REQUEST] Add support for flutter web

### ISSUE THREAD

**Issue by MagnumDingusEdu** [sarbagyastha/youtube_player_flutter#239] opened 2020-06-01 10:15 UTC
**Is your feature request related to a problem? Please describe.**
Right now, there is no good way to embed a youtube video in a flutter webapp. I've used this plugin extensively on Android and IOS, really satisfied with it.

**Describe the solution you'd like**
If possible, add support for an iframe / webview based youtube player with the same UI that we can embed as a widget. Right now, if I try to run the youtube player on web, get this error : 

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building RawYoutubePlayer(dirty, dependencies:
[InheritedYoutubePlayer], state: _RawYoutubePlayerState#63a90):
Unsupported operation: Platform._operatingSystem
The relevant error-causing widget was:
  RawYoutubePlayer
```

**Describe alternatives you've considered**
I've tried embedding youtube's official embed player in an iframe but it doesn't seem to work for me.

**Comment by sarbagyastha** [comment] 2020-06-01 10:35
Duplicate of #58.

**Closed by sarbagyastha** 2020-06-01 10:35 UTC
Labels: enhancement
