### ISSUE TITLE
 want to hide the header of youtube during playback

### ISSUE THREAD

**Issue by manabu0926** [sarbagyastha/youtube_player_flutter#251] opened 2020-06-10 13:43 UTC
[Current status]
see this picture.
![issue](https://user-images.githubusercontent.com/43611707/84274679-204d2b00-ab6b-11ea-9063-a021c2a7e06d.png)

I can't remove the header of the retrieved video.

[Ideal condition]
https://github.com/sarbagyastha/youtube_player_flutter

The state as displayed in README.md
![スクリーンショット 2020-06-10 22 40 52](https://user-images.githubusercontent.com/43611707/84275121-a49fae00-ab6b-11ea-96d3-b2efcf81a786.png)

How should I set it to display like this?
I would be happy if you could tell me.
thanks.

**Comment by sarbagyastha** [comment] 2020-06-22 03:06
Duplicate of #227

**Closed by sarbagyastha** 2020-06-22 03:06 UTC
Labels: enhancement
