### ISSUE TITLE
[BUG] 3.7 iOS build bug

### ISSUE THREAD

**Issue by serendipity1004** [sarbagyastha/youtube_player_flutter#784] opened 2023-02-03 02:43 UTC
flutter doctor
```shell
[✓] Flutter (Channel stable, 3.7.0, on macOS 12.4 21F79 darwin-arm64, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
[✓] VS Code (version 1.68.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

when I add following dependencies and run on iOS I get below error

```yaml
  youtube_player_flutter: 8.1.2
  dio: 4.0.6
```

**Error**

```shell
Running Xcode build...
Xcode build done.                                            4.1s
Failed to build iOS app
Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/jihochoi/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.7.2+3/ios/Classes/MyCookieManager.swift:259:43

Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/jihochoi/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.7.2+3/ios/Classes/MyCookieManager.swift:293:43

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro Max.
```

Is there something I can do before patch is merged?

**Comment by sarbagyastha** [comment] 2023-02-03 02:54
Duplicate of #731 
Please upgrade your Xcode to latest version.

**Closed by sarbagyastha** 2023-02-03 02:54 UTC
Labels: bug
