### ISSUE TITLE
App cannot be run if webview_flutter new version added

### ISSUE THREAD

**Issue by mrifni** [sarbagyastha/youtube_player_flutter#96] opened 2019-10-21 10:32 UTC
I cant stop and install the app when `webview_flutter: ^0.3.15+1` is in the pubspec along with `youtube_player_flutter` latest version. I get this below error.

```
/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:13: error: a type with the same simple name is already defined by the single-type-import of WebViewFlutterPlugin

11:32:25.892 9 info flutter.tools import np.com.sarbagyastha.ytview.WebViewFlutterPlugin;

```

**Comment by sarbagyastha** [comment] 2019-10-21 15:23
Duplicate of #92. Reopen the issue if you feel it's not same.

**Closed by sarbagyastha** 2019-10-21 15:23 UTC

**Comment by mrifni** [comment] 2019-10-22 14:15
I am not sure if its the same. Either case how can I resolve this issue ?
