### ISSUE TITLE
I want to show video quality options to the user but i am unable to do so. Please provide me a way or if it is not present then please suggest me another library or i request you to add the feature

### ISSUE THREAD

**Issue by adiash2014** [sarbagyastha/youtube_player_flutter#391] opened 2020-11-17 12:44 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sarbagyastha** [comment] 2020-11-22 19:22
Duplicate of #83

**Closed by sarbagyastha** 2020-11-22 19:22 UTC
Labels: enhancement
