### ISSUE TITLE
How can I hide pop-up window within Youtube after stopping video in player?

### ISSUE THREAD

**Issue by sk784** [sarbagyastha/youtube_player_flutter#210] opened 2020-05-09 09:54 UTC
![Screenshot_20200509-125220](https://user-images.githubusercontent.com/44239544/81470583-1a72cb80-91f4-11ea-95bd-887dce681423.png)

**Comment by sarbagyastha** [comment] 2020-05-10 13:54
Iframe API doesn't provides any way to hide those.

**Comment by designwithshoeb** [comment] 2020-05-12 00:12
you hide it with javascript function
pull request for that 
[pull request](https://github.com/sarbagyastha/youtube_player_flutter/pull/216)

**Comment by kamathprasad9** [comment] 2020-05-19 13:31
> you can hide it with javascript function
> [pull request for that ](https://github.com/sarbagyastha/youtube_player_flutter/pull/216)

Hey there, i tried out implementing your edit in my personal project. It didnt work out. Did it work well with you? If yes share the screenshots please

**Comment by sarbagyastha** [comment] 2020-05-31 17:45
Duplicate of #227

**Closed by sarbagyastha** 2020-05-31 17:45 UTC
Labels: wontfix
