### ISSUE TITLE
can't play on iOS , iPhone 6

### ISSUE THREAD

**Issue by singh-saheb** [sarbagyastha/youtube_player_flutter#90] opened 2019-10-19 08:55 UTC
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'loadById("Wvs1h5T4iBE", 0)'
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: loadById, WKJavaScriptExceptionColumnNumber=9, WKJavaScriptExceptionSourceURL=about:blank, NSLocalizedDescription=A JavaScript exception occurred})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript (package:webview_flutter/src/webview_method_channel.dart:90:21)
#3      WebViewController.evaluateJavascript (package:webview_flutter/webview_flutter.dart:626:39)
#4      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:553:30)
#5      YoutubePlayerController.load (package:youtube_player_flutter/src/youtube_player.dart:572:7)
#6      _YoutubePlayerState.listener (package:youtube_player_flutter/src/youtube_player.dart:222:24)
<asynchronous suspension>
#7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
#8      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:273:5)
#9      __PlayerState.build.<anonymous closure> (package:youtube_player_flutter/src/player.dart:186:29)
#10     _PlatformCallbacksHandler.onPageFinished (package:webview_flutter/webview_flutter.dart:453:15)
#11     MethodChannelWebViewPlatform._onMethodCall (package:webview_flutter/src/webview_method_channel.dart:39:35)
<asynchronous suspension>
#12     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:397:55)
<asynchronous suspension>
#13     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:365:54)
#14     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binary_messenger.dart:110:33)
<asynchronous suspension>
#15     _invoke3.<anonymous closure> (dart:ui/hooks.dart:293:15)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _invoke3 (dart:ui/hooks.dart:292:10)
#20     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)

this is the error that I'm getting

**Comment by sarbagyastha** [comment] 2019-10-19 12:00
Could you please try with the latest version. I think you're using older version.

**Comment by sarbagyastha** [comment] 2019-10-21 15:35
Please update to version 5 and try again. Duplicate of #79

**Closed by sarbagyastha** 2019-10-21 15:35 UTC
