### ISSUE TITLE
How to keep play video while changing fullscreen or portrait

### ISSUE THREAD

**Issue by nrbn** [sarbagyastha/youtube_player_flutter#275] opened 2020-06-26 14:54 UTC
When i press fullscreen while video is playing, video is paused. Any eventlistener for when fullscreenbutton pressed? How to keep play video while changing fullscreen or portrait?

**Comment by nrbn** [comment] 2020-06-26 15:51
![image](https://user-images.githubusercontent.com/10879727/85876158-9a211d80-b7d5-11ea-9275-2ba6f92d3426.png)

I have tried this, onenterfullscreen, but it does not work.

**Comment by dwikyhardi** [comment] 2020-07-06 17:41
@sarbagyastha any advice for this problem??

**Comment by sarbagyastha** [comment] 2020-07-12 11:06
Duplicate of #50

**Closed by sarbagyastha** 2020-07-12 11:06 UTC
Labels: bug
