### ISSUE TITLE
Disposing the controller with back button in new package

### ISSUE THREAD

**Issue by dheerajsarwaiya** [sarbagyastha/youtube_player_flutter#295] opened 2020-07-15 17:52 UTC
HI, 
I am getting the following error, when I hit back button from a page with youtube video. 

i am using youtube_player_iframe on the web. (it works perfectly fine on android).

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ═════════════════════════════
The following JSNoSuchMethodError was thrown building
Overlay-[LabeledGlobalKey<OverlayState>#9a698](state: OverlayState#fc15f(entries:
[OverlayEntry#d7e14(opaque: true; maintainState: false), OverlayEntry#beb31(opaque: false;
maintainState: true), OverlayEntry#11da2(opaque: true; maintainState: false),
OverlayEntry#6b51a(opaque: false; maintainState: true)])):
NoSuchMethodError: invalid member on null: 'postMessage'

When the exception was thrown, this was the stack:
packages/youtube_player_iframe/src/players/youtube_player_web.dart 170:16  [_callMethod]
packages/youtube_player_iframe/src/controller.dart 97:35                   pause
packages/notesapp/notes/youtube_local_player.dart 64:17                    deactivate
packages/flutter/src/widgets/framework.dart 4731:12                        deactivate
packages/flutter/src/widgets/framework.dart 1945:12                        _deactivateRecursively

-------------------------------

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.0)
[✓] Connected device (3 available)

Thanks.. (good work with new package :))

**Comment by dheerajsarwaiya** [comment] 2020-07-16 01:06
I was making mistake.. 
when I used  _controller.close(); in the dispose, the error went away.
Closing it.

**Comment by dheerajsarwaiya** [comment] 2020-07-16 01:19
oops getting a new error after pressing the back button from a youtube video page and then going to another page with youtube video. 

![Screenshot from 2020-07-15 18-17-27](https://user-images.githubusercontent.com/18539875/87615462-ac50f600-c6c7-11ea-8ec6-c9626a619cf6.png)

**Comment by sarbagyastha** [comment] 2020-07-17 03:58
Duplicate of #300

**Closed by sarbagyastha** 2020-07-17 03:58 UTC

**Comment by akshayru** [comment] 2020-07-20 20:22
Any update on this, i see #300  is marked duplicate.
