### ISSUE TITLE
dear friend please add quality parameter 

### ISSUE THREAD

**Issue by shailendra-rajpoot** [sarbagyastha/youtube_player_flutter#291] opened 2020-07-13 18:25 UTC
dear friend please add quality parameter i m waiting long time please do this.

**Comment by aqeelshamz** [comment] 2020-10-20 02:04
I'm also waiting for a setPlaybackQuality() method.

**Comment by sarbagyastha** [comment] 2020-11-22 19:23
Duplicate of #83

**Closed by sarbagyastha** 2020-11-22 19:23 UTC
Labels: enhancement
