### ISSUE TITLE
[BUG] Error on update android system webview to version 81.0.4044.117

### ISSUE THREAD

**Issue by DiegoLimeiradaSilva** [sarbagyastha/youtube_player_flutter#201] opened 2020-04-28 10:44 UTC
good morning, after updating the android system webview to version 81.0.4044.117 the player stopped working closes the application when it opens .. i uninstalled the webview update for testing and it works again. you can verify?

`I/WebViewFactory(31714): Loading com.google.android.webview version 81.0.4044.117 (code 404411733)
W/Gralloc3(31714): allocator 3.x is not supported
I/cr_LibraryLoader(31714): Loaded native library version number "81.0.4044.117"
D/ConnectivityManager(31714): requestNetwork; CallingUid : 10278, CallingPid : 31714, PackageName : br.com.vivensis.vsmvendas
D/ConnectivityManager(31714): requestNetwork; CallingUid : 10278, CallingPid : 31714, PackageName : br.com.vivensis.vsmvendas
W/ensis.vsmvenda(31714): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media(31714): Requires BLUETOOTH permission
I/MultiWindowDecorSupport(31714): updateCaptionType >> DecorView@60f7737[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/MultiWindowDecorSupport(31714): setCaptionType = 0, DecorView = DecorView@60f7737[]
D/ViewRootImpl@c048c0e[MainActivity](31714): setView = com.android.internal.policy.DecorView@60f7737 TM=true MM=false
D/ConnectivityManager(31714): requestNetwork; CallingUid : 10278, CallingPid : 31714, PackageName : br.com.vivensis.vsmvendas  
D/ConnectivityManager(31714): requestNetwork; CallingUid : 10278, CallingPid : 31714, PackageName : br.com.vivensis.vsmvendas  
V/InputMethodManager(31714): Not IME target window, ignoring
D/ViewRootImpl@c048c0e[MainActivity](31714): Relayout returned: old=(0,0,1080,608) new=(0,0,1080,608) req=(1080,608)0 dur=8 res=0x7 s={true 526182440960} ch=true
D/OpenGLRenderer(31714): createReliableSurface : 0x7aa8c07640, 0x7a82eae000
E/DecorView(31714): mWindow.mActivityCurrentConfig is null
W/AudioCapabilities(31714): Unsupported mime audio/x-ima
W/AudioCapabilities(31714): Unsupported mime audio/x-ape
W/AudioCapabilities(31714): Unsupported mime audio/mpeg-L1
W/AudioCapabilities(31714): Unsupported mime audio/mpeg-L2
W/AudioCapabilities(31714): Unsupported mime audio/x-ms-wma
W/VideoCapabilities(31714): Unsupported mime video/mp43
W/VideoCapabilities(31714): Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities(31714): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(31714): Unrecognized profile/level 32768/64 for video/mp4v-es
W/VideoCapabilities(31714): Unsupported mime video/wvc1
W/VideoCapabilities(31714): Unsupported mime video/x-ms-wmv7
W/VideoCapabilities(31714): Unsupported mime video/x-ms-wmv8
D/ViewRootImpl@c048c0e[MainActivity](31714): MSG_RESIZED: frame=(0,0,1080,608) ci=(0,0,0,0) vi=(0,0,0,0) or=2
W/chromium(31714): [WARNING:minidump_to_upload_parameters.cc(67)] duplicate annotation name ptype, discarding value browser
D/NetworkSecurityConfig(31714): No Network Security Config specified, using platform default
I/chromium(31714): [INFO:CONSOLE(388)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vflXhArfp/www-widgetapi.js (388)
D/SensorManager(31714): registerListener :: 20, Game Rotation Vector  Non-wakeup, 16666, 0,  
E/chromium(31714): [ERROR:validation_errors.cc(76)] Invalid message: VALIDATION_ERROR_DESERIALIZATION_FAILED (content.mojom.SynchronousCompositorControlHost.0 )
E/chromium(31714): [ERROR:render_process_host_impl.cc(4867)] Terminating render process for bad Mojo message: Received bad user message: Validation failed for content.mojom.SynchronousCompositorControlHost.0  [VALIDATION_ERROR_DESERIALIZATION_FAILED (content.mojom.SynchronousCompositorControlHost.0 )
E/chromium(31714): [ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 123
D/SensorManager(31714): unregisterListener :: 20, Game Rotation Vector  Non-wakeup,  
E/InputMethodManager(31714): b/117267690: Failed to get fallback IMM with expected displayId=56 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{5e8fbe2 VFEDHVC.. ........ 0,0-1080,608}
D/InputMethodManager(31714): HSIFW - flag : 0 Pid : 31714
I/InputMethodManager(31714): hideSoftInputFromWindow ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :io.flutter.embedding.android.FlutterView{3be4b73 VFE...... .F....I. 0,0-1080,2076}
E/chromium(31714): [ERROR:aw_browser_terminator.cc(125)] Renderer process (32700) crash detected (code -1).
E/chromium(31714): [ERROR:aw_browser_terminator.cc(90)] Render process (32700) kill (OOM or update) wasn't handed by all associated webviews, killing application.
Lost connection to `device.``

**Comment by giovanidebiagi** [comment] 2020-04-28 10:55
Facing the same issue here.

**Comment by kiranjisac** [comment] 2020-05-02 17:07
Same issue

**Comment by BrutalCoding** [comment] 2020-05-08 22:35
Getting something about picture-in-picture too, console gets spammed:
I/chromium(28821): [INFO:CONSOLE(382)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vflcv97xo/www-widgetapi.js (382)
E/SensorManager(28821): registerListenerImpl sensorName:Game Rotation Vector  Non-wakeup,isWakeUpSensor:false,callingApp: com.brutalcoding.purrgames,callingPid:28821,callingUid:10405
E/SensorManager(28821): unregisterListenerImpl sensorName:Game Rotation Vector  Non-wakeup,isWakeUpSensor:false,callingApp: com.brutalcoding.purrgames,callingPid:28821,callingUid:10405

**Comment by BrutalCoding** [comment] 2020-05-08 22:37
Getting something about picture-in-picture too, console gets spammed:
```
I/chromium(28821): [INFO:CONSOLE(382)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vflcv97xo/www-widgetapi.js (382)
E/SensorManager(28821): registerListenerImpl sensorName:Game Rotation Vector  Non-wakeup,isWakeUpSensor:false,callingApp: com.example.myapp,callingPid:28821,callingUid:10405
E/SensorManager(28821): unregisterListenerImpl sensorName:Game Rotation Vector  Non-wakeup,isWakeUpSensor:false,callingApp: com.example.myapp,callingPid:28821,callingUid:10405
```

**Comment by sarbagyastha** [comment] 2020-05-31 17:39
Duplicate of #194

**Closed by sarbagyastha** 2020-05-31 17:39 UTC
Labels: bug
