### ISSUE TITLE
Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript ... )

### ISSUE THREAD

**Issue by robin7331** [sarbagyastha/youtube_player_flutter#2] opened 2019-04-15 17:27 UTC
Hey there!

This package seemed to look pretty cool so I gave it a shot.
Unfortunately I get this error under iOS (haven't tested Android yet) when I hit the play button.

> 19:22:03.079 282 info flutter.tools [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'player.cueVideoById("secret-but-correct-video-id", 0)'

> 19:22:03.079 283 info flutter.tools Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type})

I did run `pod install` and also `flutter clean`. The video thumbnail is showing up in my view so I guess thats at least a partial success.

**Comment by naval41** [comment] 2019-04-16 01:11
I am facing same error :

 [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'player.loadVideoById("iLnmTe5Q2Qw", 0)'
Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
<asynchronous suspension>
#2      WebViewController.evaluateJavascript (package:ytview/ytview.dart:590:22)
<asynchronous suspension>

**Comment by sarbagyastha** [comment] 2019-04-16 03:09
Thanks for reporting issue 😊 . The plugin is completely tested on Android only. Performing tests on iOS currently. Will push new version after tests complete, before this weekend.

**Comment by jorg1piano** [comment] 2019-04-19 15:46
Have the same issue, works great on android but on iOS I get the exception:
   
Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'player.playVideo()'
Error Domain=WKErrorDomain Code=2 "The Web Content process was terminated" UserInfo={NSLocalizedDescription=The Web Content process was terminated})

**Comment by janvandenberg** [comment] 2019-04-20 07:13
+ 1 and thanks for creating this plugin @sarbagyastha

**Comment by sarbagyastha** [comment] 2019-04-21 12:14
Tested new [Version 1.1.0] on iOS device and it works as intended, _but in simulator video starts playing only after 4-5 minutes (although the above mentioned error shows up) in my case._ 
Can you guys check whether or not it is working on real iOS device as well as simulator.

**Comment by jorg1piano** [comment] 2019-04-21 12:40
@sarbagyastha Still getting the same exception on iPhone 6s. Running 12.1.4

**Comment by dmazlum** [comment] 2019-04-21 12:58
Hello,

@sarbagyastha Still getting the same exception too on iPhone 8. Running 12.1.2

**Comment by janvandenberg** [comment] 2019-04-21 19:16
Hi @sarbagyastha I've tested v1.1.0 on both a iOS 11 and 12 simulators (iPhone X, iPhone 8 etc) and a physical device (iPhone X) and it doesn't seem to be fixed.

I did manage to see a playing video on an iOS 11 simulator at one time, but only after 4-5 minutes like you described. When I restarted the simulator I got the error again:

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'player.playVideo()'
Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type})
```

**Comment by sarbagyastha** [comment] 2019-04-22 05:40
Done a little bit of debugging with Safari Web inspector, seems like the issue might be due to XHR ads related files. Will have to rewrite the iOS part i guess, so will take some time. If someone finds out workaround then a PR will be much appreciated. 😊

**Comment by pmrajani** [comment] 2019-04-25 07:54
Compiler message:
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/youtube_player_flutter-1.1.0/lib/src/youtube_player.dart:388:53: Error: The argument type 'Map<dynamic, dynamic>' can't be assigned to the parameter type 'Set<AudiovisualMediaTypes>'.
 - 'Map' is from 'dart:core'.
 - 'Set' is from 'dart:core'.
 - 'AudiovisualMediaTypes' is from 'package:ytview/ytview.dart' ('file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/ytview-0.0.7+3/lib/ytview.dart').
Try changing the type of the parameter, or casting the argument to 'Set<AudiovisualMediaTypes>'.
          mediaTypesRequiringUserActionForPlayback: {},
                                                    ^
Compiler failed on D:\AndroidStudioWorkspace\FlutterApps\my_smart_app\lib\main.dart
         *********************************************************
WARNING: This version of image_picker will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1


Can you check what was issue, i can't run app
i am using youtube_player_flutter: ^1.1.0 plugins

**Comment by sarbagyastha** [comment] 2019-04-25 09:45
@pmrajani , can you report with `flutter doctor -v` output.

**Comment by pmrajani** [comment] 2019-04-25 09:53
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.1], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

@sarbagyastha Here it is

**Comment by pmrajani** [comment] 2019-04-25 09:59
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.1], locale en-US)
    • Flutter version 1.1.8 at C:\src\flutter
    • Framework revision 985ccb6d14 (4 months ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
@sarbagyastha

**Comment by sarbagyastha** [comment] 2019-04-25 10:03
You're using older version of dart.. run `flutter upgrade` and the issue should be fixed. 
Note: Set notation was only introduced in Dart 2.1.2 for Flutter.

**Comment by pmrajani** [comment] 2019-04-25 11:49
@sarbagyastha it's works now thank you.

**Comment by dmazlum** [comment] 2019-04-29 07:21
> Done a little bit of debugging with Safari Web inspector, seems like the issue might be due to XHR ads related files. Will have to rewrite the iOS part i guess, so will take some time. If someone finds out workaround then a PR will be much appreciated.

Hello how about that problem? I am waiting your upgrade.

**Comment by abeeriqbal** [comment] 2019-04-29 07:59
Please fix  Failed evaluating JavaScript, JavaScript string was: 'player.playVideo()' issue ASAP.

**Comment by sarbagyastha** [comment] 2019-04-30 02:42
@dmazlum @abeeriqbal , currently having a tight schedule so will work on it as soon I get adequate time for it.

**Comment by abeeriqbal** [comment] 2019-05-09 04:36
> @dmazlum @abeeriqbal , currently having a tight schedule so will work on it as soon I get adequate time for it.

Any update?

**Comment by dmazlum** [comment] 2019-05-09 06:52
@abeeriqbal there is no update. I changed my player to webview. I embeded youtube code in webview. This is temporary solution. cheers

**Comment by SandyAra** [comment] 2019-05-09 09:12
Any Update ?

**Comment by silentsonata** [comment] 2019-05-09 16:21
This bug is affecting me also. Love the plugin though!

**Comment by sarbagyastha** [comment] 2019-05-11 13:41
Sorry folks, due to lack of spare time I couldn't work on the issue. I will work on it from next weekend onwards.

**Comment by sarbagyastha** [comment] 2019-06-04 02:05
The issue is finally fixed and will be updating the plugin tonight. It's working on iOS now.
https://imgur.com/L19WXgK

**Closed** 2019-06-08 09:26 UTC
Labels: WIP

**Comment by Fuchs1990** [comment] 2019-06-24 18:18
Hey, I just upgraded to 3.0.0+1 but I still have a JavaScript Issue on iOS.
The following error log is from your Sample App which I checked out.

This error appears when the app is started.
> [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'loadById("iLnmTe5Q2Qw", 0)'
> Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=79, WKJavaScriptExceptionMessage=TypeError: player.loadVideoById is not a function. (In 'player.loadVideoById(id, startAt)', 'player.loadVideoById' is undefined), WKJavaScriptExceptionColumnNumber=25, WKJavaScriptExceptionSourceURL=https://sarbagyadhaubanjar.github.io/youtube_player/player-revised.js, NSLocalizedDescription=A JavaScript exception occurred})
> #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
> #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
> <asynchronous suspension>
> #2      MethodChannelWebViewPlatform.evaluateJavascript (package:ytview/src/webview_method_channel.dart:90:21)
> #3      WebViewController.evaluateJavascript (package:ytview/ytview.dart:579:39)
> #4      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:580:30)
> #5      YoutubePlayerController.load (package:youtube_player_flutter/src/youtube_player.dart:594:7)
> #6      __PlayerState.build.<anonymous closure> (package:youtube_player_flutter/src/youtube_player.dart:462:37)
> #7      _PlatformCallbacksHandler.onPageFinished (package:ytview/ytview.dart:406:15)
> #8      MethodChannelWebViewPlatform._onMethodCall (package:ytview/src/webview_method_channel.dart:39:35)
> #9      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
> #10     MethodChannelWebViewPlatform._onMethodCall (package:ytview/src/webview_method_channel.dart:26:29)
> #11     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:383:55)
> #12     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
> #13     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:380:39)
> #14     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:351:54)
> #15     BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:76:33)
> #16     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
> #17     BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:44)
> #18     _invoke3.<anonymous closure> (dart:ui/hooks.dart:263:15)
> #19     _rootRun (dart:async/zone.dart:1124:13)
> #20     _CustomZone.run (dart:async/zone.dart:1021:19)
> #21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> #22     _invoke3 (dart:ui/hooks.dart:262:10)
> #23     _dispatchPlatformMessage (dart:ui/hooks.dart:136:5)

The following error appears when I press the play button on the video.

> [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'play()'
> Error Domain=WKErrorDomain Code=1 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred})
> #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
> #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
> <asynchronous suspension>
> #2      MethodChannelWebViewPlatform.evaluateJavascript (package:ytview/src/webview_method_channel.dart:90:21)
> #3      WebViewController.evaluateJavascript (package:ytview/ytview.dart:579:39)
> #4      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:580:30)
> #5      YoutubePlayerController.play (package:youtube_player_flutter/src/youtube_player.dart:587:18)
> #6      _PlayPauseButtonState.build.<anonymous closure> (package:youtube_player_flutter/src/controls.dart:80:64)
> #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
> #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
> #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
> #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
> #11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
> #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
> #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
> #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
> #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
> #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
> #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
> #18     _rootRunUnary (dart:async/zone.dart:1136:13)
> #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
> #21     _invoke1 (dart:ui/hooks.dart:233:10)
> #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)

**Comment by asada03** [comment] 2019-06-29 13:51
I just started using youtube_player_flutter and testing on an iPhone XR I still get the same error.

I am using

dependencies:
  youtube_player_flutter: ^3.0.0+1

Is this correct?
What can I do to fix the problem?

Thanks

**Comment by MohamedGhoneim** [comment] 2019-07-13 09:37
> I am facing same error :
> 
> [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'player.loadVideoById("iLnmTe5Q2Qw", 0)'
> Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type})
> #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
> #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
> 
> #2 WebViewController.evaluateJavascript (package:ytview/ytview.dart:590:22)

Hello,

@sarbagyastha Still getting the same exception too on iPhone 8. Running 12.1.2

**Comment by MohamedGhoneim** [comment] 2019-07-13 09:38
> I just started using youtube_player_flutter and testing on an iPhone XR I still get the error.
> 
> On the Android emulator the video starts automatically and not on the iPhone.
> 
> When I click play on the video I get:
> 
> [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'play()'
> Error Domain=WKErrorDomain Code=1 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred})
> 
> I am using
> 
> dependencies:
> youtube_player_flutter: ^3.0.0+1
> 
> What can I do to fix the problem?
> 
> Thanks

Hello,

@sarbagyastha Still getting the same exception too on iPhone 8. Running 12.1.2

**Comment by theolm** [comment] 2019-07-22 16:47
@sarbagyastha same error here.
Flutter version: 1.7.8+hotfix-3
youtube_player_flutter: ^3.0.0+1
device: iPhone 8 and iPhone X with iOS 12.3.1

**Comment by frgmt** [comment] 2019-10-28 06:57
@sarbagyastha I had the same issue. In my case, when value.isReady is still false, I got an error. So, I modified to display the indicator and wait until isReady changes.

**Comment by sarbagyastha** [comment] 2019-11-02 16:07
@frgmt Done in [Version 6.0.0](https://pub.dev/packages/youtube_player_flutter#-changelog-tab-)

**Comment by Kronos-2701** [comment] 2023-07-11 11:53
" Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null) "

Facing this error while trying to run javascript on an iOS simulator.
@sarbagyastha
