### ISSUE TITLE
[BUG] Example app crash

### ISSUE THREAD

**Issue by zamahaka** [sarbagyastha/youtube_player_flutter#188] opened 2020-04-09 13:50 UTC
Example app crashes a few seconds after app start
branch: master ea392c7612abe1b56a86d28d1dc12f4de2d0f669 

 - Device: Pixel 4
 - OS: Android 10

Log:
```
Launching lib/main.dart on Pixel 4 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter_exampl(19940): Late-enabling -Xcheck:jni
E/flutter_exampl(19940): Unknown bits set in runtime_flags: 0x8000
W/flutter_exampl(19940): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter_exampl(19940): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter_exampl(19940): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/flutter_exampl(19940): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
Debug service listening on ws://127.0.0.1:61623/i77bVekWzis=/ws
Syncing files to device Pixel 4...
I/WebViewFactory(19940): Loading com.google.android.webview version 81.0.4044.96 (code 404409633)
I/cr_LibraryLoader(19940): Loaded native library version number "81.0.4044.96"
W/chromium(19940): [WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
W/flutter_exampl(19940): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media(19940): Requires BLUETOOTH permission
W/VideoCapabilities(19940): Unsupported mime image/vnd.android.heic
W/chromium(19940): [WARNING:minidump_to_upload_parameters.cc(67)] duplicate annotation name ptype, discarding value browser
D/NetworkSecurityConfig(19940): No Network Security Config specified, using platform default
I/chromium(19940): [INFO:CONSOLE(228)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vflHkwjNO/www-widgetapi.js (228)
E/chromium(19940): [ERROR:validation_errors.cc(76)] Invalid message: VALIDATION_ERROR_DESERIALIZATION_FAILED (content.mojom.SynchronousCompositorControlHost.0 )
E/chromium(19940): [ERROR:render_process_host_impl.cc(4867)] Terminating render process for bad Mojo message: Received bad user message: Validation failed for content.mojom.SynchronousCompositorControlHost.0  [VALIDATION_ERROR_DESERIALIZATION_FAILED (content.mojom.SynchronousCompositorControlHost.0 )
E/chromium(19940): [ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 123
E/InputMethodManager(19940): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{6ef42ff VFEDHVC.. ........ 0,0-1080,608}
E/chromium(19940): [ERROR:aw_browser_terminator.cc(125)] Renderer process (19998) crash detected (code -1).
E/chromium(19940): [ERROR:aw_browser_terminator.cc(90)] Render process (19998) kill (OOM or update) wasn't handed by all associated webviews, killing application.
Lost connection to device.
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:61623/i77bVekWzis=/
```
Flutter doctor:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/zamahaka/Library/flutter
    • Framework revision 0b8abb4724 (8 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/zamahaka/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Pixel 4  • 192.168.0.101:5555                   • android-arm64 • Android 10 (API 29)
    • iPhone X • CEBFDF16-A226-4012-B2D9-5C94ED8E4370 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-0 (simulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by zamahaka** [comment] 2020-04-09 13:55
Video:
![crash_vid](https://user-images.githubusercontent.com/17888913/78902799-f13f0e00-7a82-11ea-8318-5294a0c47f3d.gif)

**Comment by zamahaka** [comment] 2020-04-09 15:08
Same for hotfix.9
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/zamahaka/Library/flutter
    • Framework revision f139b11009 (10 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/zamahaka/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/zamahaka/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Pixel 4  • 192.168.0.101:5555                   • android-arm64 • Android 10 (API 29)
    • iPhone X • CEBFDF16-A226-4012-B2D9-5C94ED8E4370 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-0 (simulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by ClemaX** [comment] 2020-04-15 00:56
This seems to be caused by the `forceHideAnnotation: true` flag. It was kind of hacky and has apparently been broken by this new Chromium version.

**Comment by yeahse** [comment] 2020-04-15 06:45
> This seems to be caused by the `forceHideAnnotation: true` flag. It was kind of hacky and has apparently been broken by this new Chromium version.

really appreciate

**Comment by bigzhu** [comment] 2020-04-16 06:36
In order to avoid Crash YouTube iframe play/pause button can't hide.

is anyone found a solution?

**Comment by sarbagyastha** [comment] 2020-05-31 17:51
Duplicate of #194

**Closed by sarbagyastha** 2020-05-31 17:51 UTC
Labels: bug
