### ISSUE TITLE
DragSeek beyond duration of video makes progress bar go on to multiple lines

### ISSUE THREAD

**Issue by jimmyff** [sarbagyastha/youtube_player_flutter#166] opened 2020-03-06 12:42 UTC
If you drag to seek a video beyond the length of the video I have seen the `ProgressBar` go on to multiple lines

**Comment by sarbagyastha** [comment] 2020-05-31 18:09
Closing as couldn't reproduce. Fell free to reopen with appropriate reproducible snippet if required.

**Closed by sarbagyastha** 2020-05-31 18:09 UTC
Labels: bug
