### ISSUE TITLE
Resizing the YoutubePlayer Widget stops playing the video[BUG]

### ISSUE THREAD

**Issue by Maadhav** [sarbagyastha/youtube_player_flutter#209] opened 2020-05-09 09:14 UTC
```
AnimatedContainer(
            duration: Duration(seconds: 1),
            height:  MediaQuery.of(context).size.height / (isFullScreen? 7:3),
            width: MediaQuery.of(context).size.width / (isFullScreen?2.2:1),
            child: YoutubePlayer(
              progressIndicatorColor: Colors.white,
              controller: _controller,
              showVideoProgressIndicator: true,
              bottomActions: [
                CurrentPosition(),
                ProgressBar(
                  isExpanded: true,
                  colors: ProgressBarColors(
                    playedColor: Color(0xff007084),
                    backgroundColor: Colors.black.withOpacity(0.1),
                  ),
                ),
                RemainingDuration(),
              ],
            ),
          ),
```

**Comment by sarbagyastha** [comment] 2020-05-31 18:23
Duplicate of #50

**Closed by sarbagyastha** 2020-05-31 18:23 UTC
Labels: bug
