### ISSUE TITLE
[BUG]switching to another video doesn't pause the first one

### ISSUE THREAD

**Issue by manhag** [sarbagyastha/youtube_player_flutter#214] opened 2020-05-10 22:36 UTC
**Describe the bug**
before last update  ....switching between videos .....pause the first one
now  it is not working

**To Reproduce**
initState() 
 @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  void deactivate() {
    // Pauses video while navigating to next page.
    _controller.pause();
    super.deactivate();
  }

Widget build(BuildContext context) {
   return
           YoutubePlayer(
            controller: _controller,
                showVideoProgressIndicator: true,
            progressIndicatorColor: Colors.blueAccent,

)}
**Expected behavior**
pausing previous video

**Screenshots**

**Technical Details:**
 - Device:  xiaomi redmi 8a
 - OS: android
 - Version  22

**Additional context**

**Comment by sarbagyastha** [comment] 2020-05-31 17:33
Please try with v7.0.0.

**Comment by sarbagyastha** [comment] 2020-05-31 18:28
Closing for now as couldn't reproduce. Please feel free to reopen.

**Closed by sarbagyastha** 2020-05-31 18:28 UTC
Labels: bug
