### ISSUE TITLE
[FEATURE REQUEST]  how can i make this plugin work in web browsers?

### ISSUE THREAD

**Issue by avishramgolam** [sarbagyastha/youtube_player_flutter#203] opened 2020-05-01 22:34 UTC
I wish to make this plugin work in web browsers and mobile app. any hint? any workaround?

**Comment by BrutalCoding** [comment] 2020-05-09 08:14
Haven't looked into this yet, and for sure don't know an answer to your question. But my first thought would be to make use of a widget that makes use of an iFrame when you detect your app is being used on the web. Just embed the youtube video within that iFrame. 

I just found the perfect article written by Aseem Wangoo: https://dev.to/aseemwangoo/flutter-web-and-iframe-n2d

Flutter web demo: https://fir-signin-4477d.firebaseapp.com/#/iframe (Also by him)

**Comment by BrutalCoding** [comment] 2020-05-26 12:16
> Haven't looked into this yet, and for sure don't know an answer to your question (adding functionality to this package). But my first thought would be to make use of a widget that makes use of an iFrame when you detect your app is being used on the web. Just embed the youtube video within that iFrame. 
> 
> I just found the perfect article written by Aseem Wangoo: https://dev.to/aseemwangoo/flutter-web-and-iframe-n2d
> 
> Flutter web demo: https://fir-signin-4477d.firebaseapp.com/#/iframe (Also by him)

I got it working in my app (iOS/Android/Web) but the biggest downside on Web is that the iFrame is a HTML element on top of the flutter canvas (I think), so it captures all input from the user and Flutter won't know at all.

What this means is that is for example:
- YouTube iFrames in a row or column can't be scrolled if it exceeds the page (in a scrollview).

Very annoying, and haven't found a solution yet.
Just wanted to let everyone know that is going this path like I did.

**Comment by avishramgolam** [comment] 2020-05-26 20:03
thank you so much :) hope this gets fixed quickly.

While at my place the iframe doesn't play at all :( 

I would be curious to see your codes if ever you get the chance to share with me.

**Comment by sarbagyastha** [comment] 2020-05-31 18:34
Duplicate of #58

**Closed by sarbagyastha** 2020-05-31 18:34 UTC
Labels: enhancement
