### ISSUE TITLE
[BUG] iOS inline video not working

### ISSUE THREAD

**Issue by jerlyjelly** [sarbagyastha/youtube_player_flutter#532] opened 2021-08-10 08:55 UTC
**Describe the bug**
For iOS, it opens an in app view internet browser and redirects to youtube-nocookie.com. The log says 

> [Assert] +[UIInputViewSetPlacementInvisible placementWithPlacement:]: Should not be called with an invisible placement

The video is not showing

**To Reproduce**

This is my code snippet
`SliverAppBar(
            expandedHeight: MediaQuery.of(context).size.height * 0.2,
            backgroundColor: playlistAppBarColor,
            pinned: true,
            stretch: true,
            flexibleSpace: YoutubePlayerIFrame(
              controller: YoutubePlayerController(
                  initialVideoId: 'U3Rd6bG69-c', //Add videoID.
                  params: YoutubePlayerParams(
                    // startAt: const Duration(minutes: 1, seconds: 36),
                    showControls: true,
                    showFullscreenButton: true,
                    // desktopMode: true,
                    autoPlay: true,
                    loop: true,
                    mute: true,
                    privacyEnhanced: true,
                    // useHybridComposition: true,
                  )),
            ),
          ),`

**Expected behavior**
On Android, the youtube video plays inline perfectly fine. On iOS, it opens a pop up as mentioned above and doesn't load any videos. 

**Screenshots**
![image](https://user-images.githubusercontent.com/68527525/128838222-6f6836b8-a008-475f-accc-ae7540b1ab28.png)

**Technical Details:**
 - Device: iPad 6
 - OS: iOS 14.6

**Additional context**

**Comment by PcolBP** [comment] 2021-08-11 08:49
Duplicate of #525, give there thumb up for author to notice.

**Comment by sarbagyastha** [comment] 2021-08-14 01:27
Fixed with v2.2.2

**Closed by sarbagyastha** 2021-08-14 01:27 UTC
Labels: bug
