### ISSUE TITLE
[BUG] I/flutter (27483): The controller is not ready for method calls. With latest version

### ISSUE THREAD

**Issue by madhu-1stmain** [sarbagyastha/youtube_player_flutter#156] opened 2020-02-24 08:38 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Technical Details:**

**Additional context**

**Comment by furaiev** [comment] 2020-02-28 07:00
This one is reproducible only on Simulator but works on real device.

**Comment by madhu-1stmain** [comment] 2020-03-02 11:04
Same issue on real device also

**Comment by madhu-1stmain** [comment] 2020-03-03 11:15
Any update on this, we are really stuck because of this.

**Comment by jimmyff** [comment] 2020-03-17 11:30
I also have this issue which is preventing me for putting app in to App Store.

Not sure if it's related to:
https://github.com/sarbagyastha/youtube_player_flutter/issues/149#issuecomment-589932914

**Comment by sarbagyastha** [comment] 2020-05-31 18:19
Duplicate of #120

**Closed by sarbagyastha** 2020-05-31 18:19 UTC
Labels: bug
