### ISSUE TITLE
Add Quality option

### ISSUE THREAD

**Issue by Khawlah-Mohammed** [sarbagyastha/youtube_player_flutter#223] opened 2020-05-17 15:35 UTC
Add quality option to default Controls

**Comment by habeebrahman021** [comment] 2020-05-21 19:41
Waiting for this feature.

**Comment by shaheemMPM** [comment] 2020-05-31 02:27
My application very much depends on this package, so if you can add this feature it will be a good boost in UX of my application.

I've one more query regarding Quality.!

Does this plugin automatically change video quality according to internet strength as normal youtube players do??

**Comment by sarbagyastha** [comment] 2020-05-31 14:36
@shaheemMPM  Yes the quality of video changes wrt to network bandwidth and screen sizes. But there's no way to change the quality manually.

**Comment by shaheemMPM** [comment] 2020-06-01 01:27
> @shaheemMPM  Yes the quality of video changes wrt to network bandwidth and screen sizes. But there's no way to change the quality manually. 

Ok, Thanks.

**Comment by shaheemMPM** [comment] 2020-07-13 13:56
@sarbagyastha are you planning to add this feature in near future?

**Comment by sarbagyastha** [comment] 2020-07-13 14:04
@shaheemMPM The feature is not supported by iFrame Player API.

**Comment by shaheemMPM** [comment] 2020-07-13 15:05
@sarbagyastha that's unfortunate, I asked since you reopened the thread

**Comment by sarbagyastha** [comment] 2020-11-22 19:24
Duplicate of #83

**Closed by sarbagyastha** 2020-11-22 19:24 UTC
Labels: enhancement
