### ISSUE TITLE
[BUG] Player crashes suddently (worked until some days ago). Maybe related to Chrome 81?

### ISSUE THREAD

**Issue by pdivita** [sarbagyastha/youtube_player_flutter#194] opened 2020-04-16 10:08 UTC
**Describe the bug**
Player crashes on Android (I'm using Mi 9T with Android 10). It worked like a charm until few days ago.
I don't know if it is related to the version of Chrome. Tried with emulator with Chrome 80 and it works.

Edit: Confirm it is caused by Chrome 81 and "forceHideAnnotations: true" as discovered by [this comment](https://github.com/sarbagyastha/youtube_player_flutter/issues/194#issuecomment-615095009). Partial fix is do not use forceHideAnnotations.

**To Reproduce**
Play the video with any ID (I tried with id: U_XsRZXL2Ic )

**Expected behavior**
Player should play the video

**Technical Details:**
 - Device: Android Mi 9T
 - OS: Android 10 Q
 - Version 29

**Additional context**
App crashes and this is the log:

I/WebViewFactory( 6349): Loading com.google.android.webview version 81.0.4044.111 (code 404411133)
I/cr_LibraryLoader( 6349): Loaded native library version number "81.0.4044.111"
W/Gralloc3( 6349): allocator 3.x is not supported
D/EgretLoader( 6349): EgretLoader(Context context)
D/EgretLoader( 6349): The context is not activity
W/erocks.eventda( 6349): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media( 6349): Requires BLUETOOTH permission
W/VideoCapabilities( 6349): Unsupported mime image/vnd.android.heic
W/VideoCapabilities( 6349): Unsupported mime video/divx
W/VideoCapabilities( 6349): Unsupported mime video/divx4
W/VideoCapabilities( 6349): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities( 6349): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities( 6349): Unsupported mime video/x-ms-wmv
W/ContentCatcher( 6349): Failed to notify a WebView
W/chromium( 6349): [WARNING:minidump_to_upload_parameters.cc(67)] duplicate annotation name ptype, discarding value browser
D/NetworkSecurityConfig( 6349): No Network Security Config specified, using platform default
I/chromium( 6349): [INFO:CONSOLE(384)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vflLsCj8Z/www-widgetapi.js (384)
E/chromium( 6349): [ERROR:validation_errors.cc(76)] Invalid message: VALIDATION_ERROR_DESERIALIZATION_FAILED (content.mojom.SynchronousCompositorControlHost.0 )
E/chromium( 6349): [ERROR:render_process_host_impl.cc(4867)] Terminating render process for bad Mojo message: Received bad user message: Validation failed for content.mojom.SynchronousCompositorControlHost.0  [VALIDATION_ERROR_DESERIALIZATION_FAILED (content.mojom.SynchronousCompositorControlHost.0 )
E/chromium( 6349): [ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 123
W/Looper  ( 6349): Slow Looper main: doFrame is 331ms late
E/InputMethodManager( 6349): b/117267690: Failed to get fallback IMM with expected displayId=10 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{3118869 VFEDHVC.. ........ 0,0-987,555}
E/chromium( 6349): [ERROR:aw_browser_terminator.cc(125)] Renderer process (6465) crash detected (code -1).
E/chromium( 6349): [ERROR:aw_browser_terminator.cc(90)] Render process (6465) kill (OOM or update) wasn't handed by all associated webviews, killing application.

**Comment by Dansp** [comment] 2020-04-16 14:58
Same problem with me, the app crashes when play some video.

**Comment by almazamangaliev** [comment] 2020-04-16 15:52
Same problem with me, app crashes

**Comment by mamm26** [comment] 2020-04-16 18:13
Crash on Samsung Note 8 (Android 9).
Black screen (and sound works) on Samsung S6 (Android 7.0).

**Comment by sarbagyastha** [comment] 2020-04-17 01:59
Seems to be working fine. Tested on:
- Flutter stable, dev and master channels
- Android P with Chrome 80, Android R with Chrome 82 (Emulator)

**Comment by ManKeomorakort** [comment] 2020-04-17 03:03
I got the same problem for android which install chrome 81.* and Iphone always stuck at loading screen

**Comment by ManKeomorakort** [comment] 2020-04-17 05:16
I update to youtube_player_flutter 6.1.0+7, but the error still exist.
```
I/WebViewFactory(26403): Loading com.android.chrome version 81.0.4044.111 (code 404411123)
I/cr_LibraryLoader(26403): Loaded native library version number "81.0.4044.111"
W/sia.wiki.schoo(26403): Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (light greylist, reflection)
E/chromium(26403): [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/com.poscarasia.wiki.school/cache/WebView/Crashpad: No such file or directory (2)
W/sia.wiki.schoo(26403): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (light greylist, reflection)
W/VideoCapabilities(26403): Unsupported mime video/divx
W/VideoCapabilities(26403): Unsupported mime video/divx311
W/VideoCapabilities(26403): Unsupported mime video/divx4
W/VideoCapabilities(26403): Unrecognized profile 4 for video/hevc
W/VideoCapabilities(26403): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(26403): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(26403): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(26403): Unsupported mime video/x-ms-wmv
I/VideoCapabilities(26403): Unsupported profile 4 for video/mp4v-es
W/Utils   (26403): could not parse long range '175-174'
I/chromium(26403): [INFO:CONSOLE(379)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vfljfBzLT/www-widgetapi.js (379)
E/chromium(26403): [ERROR:validation_errors.cc(76)] Invalid message: VALIDATION_ERROR_DESERIALIZATION_FAILED (content.mojom.SynchronousCompositorControlHost.0 )
E/chromium(26403): [ERROR:render_process_host_impl.cc(4867)] Terminating render process for bad Mojo message: Received bad user message: Validation failed for content.mojom.SynchronousCompositorControlHost.0  [VALIDATION_ERROR_DESERIALIZATION_FAILED (content.mojom.SynchronousCompositorControlHost.0 )
E/chromium(26403): [ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 123
E/chromium(26403): [ERROR:aw_browser_terminator.cc(125)] Renderer process (26588) crash detected (code -1).
E/chromium(26403): [ERROR:aw_browser_terminator.cc(90)] Render process (26588) kill (OOM or update) wasn't handed by all associated webviews, killing application.
Lost connection to device.
```

**Comment by ManKeomorakort** [comment] 2020-04-17 07:40
This seems to be caused by the forceHideAnnotation: true. So i set to false and it work.
I tested with 
 - Azus phone (Android 9, Chrome 81.0.4044.111), 
 - Samsung A50 (Android 10, 81.0.4044.111)
- Iphone XR

**Environment**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale km-KH)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)

• No issues found!

```

**Comment by pdivita** [comment] 2020-04-17 09:58
Confirm it is caused by forceHideAnnotation

**Comment by Dansp** [comment] 2020-04-17 12:35
I update to youtube_player_flutter 6.1.0+7, same error. Any solution?

**Comment by Dansp** [comment] 2020-04-17 13:11
forceHideAnnotation to false solve crashe

**Comment by ClemaX** [comment] 2020-04-17 13:12
Dupplicate of #188

**Comment by mamm26** [comment] 2020-04-17 15:02
Black screen was also fixed, any solution to hide annotations?

**Comment by nazamov** [comment] 2020-04-18 17:52
forceHideAnnotation to false also worked for me. @ManKeomorakort Thanke you very much.

**Comment by sarbagyastha** [comment] 2020-05-10 13:52
Closing this as forceHideAnnotation flag is now removed.

**Closed by sarbagyastha** 2020-05-10 13:52 UTC
Labels: bug, question

**Comment by Mactacs** [comment] 2020-07-11 14:28
Where did you place the forceHideAnnotation?

**Comment by ethanliew** [comment] 2021-05-27 09:57
just recent, any one face youtube player crash while loading youtube video  and causing whole app crashed ?
