### ISSUE TITLE
No Youtube Ads coming 

### ISSUE THREAD

**Issue by aamirzaidi** [sarbagyastha/youtube_player_flutter#285] opened 2020-07-09 09:40 UTC
No ads come from youtube ever when we run it in android. Am i missing some way to enable them. I am worried if no ads come from youtube, app might be considered illegal or the owner of video may not like it and report it.
Please help.

**Comment by ZdenekKrcal** [comment] 2020-07-10 07:21
> No ads come from youtube ever when we run it in android. Am i missing some way to enable them. I am worried if no ads come from youtube, app might be considered illegal or the owner of video may not like it and report it.
> Please help.

For me no ads is great solution. :-)

**Comment by sarbagyastha** [comment] 2020-07-10 12:52
Duplicate of #117

**Closed by sarbagyastha** 2020-07-10 12:52 UTC
